# Adapted from https://github.com/weeyin83/vm-actions
name: Deploy VM on Azure

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: [push]

jobs:
      
  # Deploy VM in Azure
  DeployVM:
    runs-on: ubuntu-latest

    steps:
    # checkout code from repo
    - name: checkout repo
      uses: actions/checkout@v1

    - name: look for ps1 file
      run: |
        ls '${{ env.OUTPUT_PATH }}/PSA'
    - name: provision virtual machine in azure
      env:
        RESOURCE_GROUP: RhodriGpu
        RESOURCE_GROUP_REGION: uksouth
        SERVER_NAME: githubactions
        ADMIN_LOGIN: rhodri
      run: >
        pwsh -command "& '${{ env.OUTPUT_PATH }}\PSA\deployVM.ps1'"
        -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}
        -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
        -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }}
        -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        -resourceGroupName $RESOURCE_GROUP
        -resourceGroupNameRegion $RESOURCE_GROUP_REGION
        -serverName $SERVER_NAME
        -adminLogin $ADMIN_LOGIN
        -adminPassword ${{ secrets.ADMIN_PASSWORD }}
    - name: log into vm
        ssh rhodri@$(az vm show -d -g RhodriGpu -n githubactions --query publicIps -o tsv)
        expect "password"
        send "${{ secrets.ADMIN_PASSWORD }}\r"
        interact
